### PR TITLE
Add asanzgom to the opendatahub-io members list

### PR DESCRIPTION
**Pull request by asanzgom**
## Description

I have joined the Operator Scrum Team on the RHODS/RHOAI Project.

@etirelli @VaishnaviHire 
## New Open Data Hub Member Requirements
- [x] New members have reviewed and acknowledged the Open Data Hub:
  - [Code of Conduct](https://github.com/opendatahub-io/opendatahub-community/blob/main/CODE_OF_CONDUCT.md)
  - [Contribution Guide](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributing.md)
  - [Community Membership Guidelines](https://github.com/opendatahub-io/opendatahub-community/blob/main/community-membership.md)
- [x] [Enabled 2FA on their GitHub account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication)

## Pull Request Requirements
- [x] New members are added in alphabetical order
- [x] Only one new member change per commit (if you add two members separate it into two commits
- [x] For individual user changes: Commit message format `Add <USERNAME> to <opendatahub-io, mlops-sig, ...>`. 
- [ ] For new team requests: Commit message format `Create <TEAMNAME>`. If the new team consists solely of existing members, you may 
- [ ] New GitHub team requests are from an existing opendatahub-io member who will function as the maintainer of the team. Each additional member will follow the same requirements for adding new members

### CODE REVIEW

**Comment by etirelli** [comment]
Please add yourself to the members section at the start of the file.

**Comment by asanzgom** [comment]
@etirelli moved my user to the opendatahub-io members list

**Comment by asanzgom** [comment]
@accorvin @cfchase @jkoehler-redhat @LaVLaS @shgriffi please, Could any of you review this PR? Thank you very much!

**Review by LaVLaS — APPROVED** [review]

**Comment by asanzgom** [comment]
Thanks, @LaVLaS for approving changes. Can you please merge and close this PR?

**Comment by asanzgom** [comment]
Thanks @accorvin !

**Pull request merged**
