### PR TITLE
Adding vaibhavjainwiz to opendatahub-io,modelmesh-serving, odh-model-co…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
…ntroller

## Description
Adding vaibhavjainwiz to opendatahub-io,modelmesh-serving, odh-model-controller

## New Open Data Hub Member Requirements
- [x] New members have reviewed and acknowledged the Open Data Hub:
  - [Code of Conduct](https://github.com/opendatahub-io/opendatahub-community/blob/main/CODE_OF_CONDUCT.md)
  - [Contribution Guide](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributing.md)
  - [Community Membership Guidelines](https://github.com/opendatahub-io/opendatahub-community/blob/main/community-membership.md)
- [x] [Enabled 2FA on their GitHub account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication)

## Pull Request Requirements
- [x] New members are added in alphabetical order
- [x] Only one new member change per commit (if you add two members separate it in two commits
- [x] For individual user changes: Commit message format `Add <USERNAME> to <opendatahub-io, mlops-sig, ...>`. 
- [x] For new team requests: Commit message format `Create <TEAMNAME>`. If the new team consists solely of existing members, you may 
- [x] New GitHub team requests are from an existing opendatahub-io member who will function as the maintainer of the team. Each additional member will follow the same requirements for adding new members

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
Changes lgtm, but Cc @Jooho @taneem-ibrahim

**Comment by Jooho** [comment]
@vaibhavjainwiz  Please add your id to 5 repos.
- modelmesh
- modelmesh-serving
- modelmesh-runtime-adapter
- rest-proxy
- odh-model-controller

**Comment by vaibhavjainwiz** [comment]
@Jooho I had added myself into mentioned repos.

**Review by Jooho — APPROVED** [review]
/lgtm

**Pull request merged**
