### PR TITLE
Write access to odh-manifests for model serving team

### PR DESCRIPTION
**Pull request by heyselbi**
## Description

Adding write access to odh-manifests for model serving team, so we can:
- create and manage issues, and be able to add labels
- manage our pull requests

All related to kserve/caikit/tgis dev work tracking in our GitHub project board.

## New Open Data Hub Member Requirements
- [x] New members have reviewed and acknowledged the Open Data Hub:
  - [Code of Conduct](https://github.com/opendatahub-io/opendatahub-community/blob/main/CODE_OF_CONDUCT.md)
  - [Contribution Guide](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributing.md)
  - [Community Membership Guidelines](https://github.com/opendatahub-io/opendatahub-community/blob/main/community-membership.md)
- [x] [Enabled 2FA on their GitHub account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication)

## Pull Request Requirements
- [ ] New members are added in alphabetical order
- [ ] Only one new member change per commit (if you add two members separate it in two commits
- [ ] For individual user changes: Commit message format `Add <USERNAME> to <opendatahub-io, mlops-sig, ...>`. 
- [ ] For new team requests: Commit message format `Create <TEAMNAME>`. If the new team consists solely of existing members, you may 
- [ ] New GitHub team requests are from an existing opendatahub-io member who will function as the maintainer of the team. Each additional member will follow the same requirements for adding new members

### CODE REVIEW

**Review by vaibhavjainwiz — APPROVED** [review]

**Review by danielezonca — APPROVED** [review]
/lgtm

**Review by Jooho — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
@anishasthana Is correct. `Triage` access is all that is needed for manage issue metadata.  

@heyselbi As part of the ODH Operator Rework (https://github.com/opendatahub-io/opendatahub-operator/issues/156) this repo will be most likely be archived by the end of the year.  You are more than welcome to manage issues here but we will be disabling issues in odh-manifests prior to officially archiving the repo.  If the goal is to managed issues related to the model serving stack they would be better suited to live in the same repo as the actual code -- OR -- you can use [opendatahub-community](https://github.com/opendatahub-io/opendatahub-community/issues) as the unified issue repo

**Comment by heyselbi** [comment]
@LaVLaS I was inquiring the write access because we have an open PR in odh-manifests (ref: https://github.com/opendatahub-io/odh-manifests/pull/838 ). So we wanted to be able to edit the issue (ref: https://github.com/opendatahub-io/odh-manifests/issues/848) related to it to better reflect it on our board.

But I could move the issue to opendatahub-community, if that is more preferable.

**Pull request closed without merging**
